# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50)),
                ('maintenance_id', models.CharField(max_length=50)),
                ('alarm_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=300)),
                ('resource_code', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=200, unique=True)),
                ('staion_name', models.CharField(max_length=300)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
        migrations.AddField(
            model_name='property',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
        migrations.AddField(
            model_name='order',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
    ]
