# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indent_status', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.District', to_field='district_name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=50, unique=True)),
                ('maintenance_id', models.CharField(max_length=50)),
                ('alarm_details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('construction_type', models.CharField(max_length=200)),
                ('tower_type', models.CharField(max_length=200)),
                ('room_type', models.CharField(max_length=200)),
                ('investment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.District', to_field='district_name')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('contract_type', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.District', to_field='district_name')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_code', models.CharField(max_length=200, unique=True)),
                ('resource_name', models.CharField(max_length=300)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.District', to_field='district_name')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=200, unique=True)),
                ('station_name', models.CharField(max_length=300)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=300)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.District', to_field='district_name')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
        migrations.AddField(
            model_name='property',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
        migrations.AddField(
            model_name='project',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
        migrations.AddField(
            model_name='order',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
        migrations.AddField(
            model_name='indent',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code'),
        ),
    ]
