# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_year',
            field=models.DecimalField(decimal_places=2, default='-0.1', max_digits=9),
            preserve_default=False,
        ),
    ]
