# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_squashed_0002_property_price_per_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='seq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
