# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Client', to_field='client_name'),
        ),
    ]
