# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160923_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.CharField(default='hello', max_length=50),
            preserve_default=False,
        ),
    ]
