# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161003_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contract_type',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
