# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20161010_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='room_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='tower_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
