# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20161004_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('construction_type', models.CharField(max_length=200)),
                ('tower_type', models.CharField(max_length=200)),
                ('room_type', models.CharField(max_length=200)),
                ('investment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
