# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20161011_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
