# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20161009_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indent_status', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('station_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Station', to_field='station_code')),
            ],
        ),
    ]
